-- Core contact submissions table
create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  message text not null,
  created_at timestamptz not null default now()
);

-- Folder-like sections for organizing public photos
create table if not exists public.photo_folders (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  sort_order integer not null default 0,
  is_public boolean not null default true,
  created_at timestamptz not null default now()
);

-- Photo records linked to folders
create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  folder_id bigint not null references public.photo_folders(id) on delete cascade,
  storage_path text not null unique,
  public_url text not null,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists photo_folders_public_sort_idx
  on public.photo_folders(is_public, sort_order, id);

create index if not exists photos_folder_sort_idx
  on public.photos(folder_id, sort_order, id);

-- Public read-only policies for landing page photo rendering
alter table public.photo_folders enable row level security;
alter table public.photos enable row level security;
alter table public.contact_submissions enable row level security;

drop policy if exists "Public can view public folders" on public.photo_folders;
create policy "Public can view public folders"
  on public.photo_folders
  for select
  using (is_public = true);

drop policy if exists "Public can view photos in public folders" on public.photos;
create policy "Public can view photos in public folders"
  on public.photos
  for select
  using (
    exists (
      select 1
      from public.photo_folders folders
      where folders.id = photos.folder_id
        and folders.is_public = true
    )
  );

-- Contact submissions are private by default.
drop policy if exists "No direct contact access" on public.contact_submissions;
create policy "No direct contact access"
  on public.contact_submissions
  for all
  using (false)
  with check (false);

-- Storage bucket for public photo assets
insert into storage.buckets (id, name, public)
values ('photo-sections', 'photo-sections', true)
on conflict (id) do nothing;
